package com.example.base.mapper;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Mon Feb 27 22:23:57 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.code1
     *
     * @mbggenerated Mon Feb 27 22:23:57 CST 2017
     */
    private Byte code1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.code2
     *
     * @mbggenerated Mon Feb 27 22:23:57 CST 2017
     */
    private Short code2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.code3
     *
     * @mbggenerated Mon Feb 27 22:23:57 CST 2017
     */
    private Integer code3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.code4
     *
     * @mbggenerated Mon Feb 27 22:23:57 CST 2017
     */
    private Integer code4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.code5
     *
     * @mbggenerated Mon Feb 27 22:23:57 CST 2017
     */
    private Long code5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.tips
     *
     * @mbggenerated Mon Feb 27 22:23:57 CST 2017
     */
    private String tips;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Mon Feb 27 22:23:57 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Mon Feb 27 22:23:57 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.code1
     *
     * @return the value of user.code1
     *
     * @mbggenerated Mon Feb 27 22:23:57 CST 2017
     */
    public Byte getCode1() {
        return code1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.code1
     *
     * @param code1 the value for user.code1
     *
     * @mbggenerated Mon Feb 27 22:23:57 CST 2017
     */
    public void setCode1(Byte code1) {
        this.code1 = code1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.code2
     *
     * @return the value of user.code2
     *
     * @mbggenerated Mon Feb 27 22:23:57 CST 2017
     */
    public Short getCode2() {
        return code2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.code2
     *
     * @param code2 the value for user.code2
     *
     * @mbggenerated Mon Feb 27 22:23:57 CST 2017
     */
    public void setCode2(Short code2) {
        this.code2 = code2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.code3
     *
     * @return the value of user.code3
     *
     * @mbggenerated Mon Feb 27 22:23:57 CST 2017
     */
    public Integer getCode3() {
        return code3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.code3
     *
     * @param code3 the value for user.code3
     *
     * @mbggenerated Mon Feb 27 22:23:57 CST 2017
     */
    public void setCode3(Integer code3) {
        this.code3 = code3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.code4
     *
     * @return the value of user.code4
     *
     * @mbggenerated Mon Feb 27 22:23:57 CST 2017
     */
    public Integer getCode4() {
        return code4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.code4
     *
     * @param code4 the value for user.code4
     *
     * @mbggenerated Mon Feb 27 22:23:57 CST 2017
     */
    public void setCode4(Integer code4) {
        this.code4 = code4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.code5
     *
     * @return the value of user.code5
     *
     * @mbggenerated Mon Feb 27 22:23:57 CST 2017
     */
    public Long getCode5() {
        return code5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.code5
     *
     * @param code5 the value for user.code5
     *
     * @mbggenerated Mon Feb 27 22:23:57 CST 2017
     */
    public void setCode5(Long code5) {
        this.code5 = code5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.tips
     *
     * @return the value of user.tips
     *
     * @mbggenerated Mon Feb 27 22:23:57 CST 2017
     */
    public String getTips() {
        return tips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.tips
     *
     * @param tips the value for user.tips
     *
     * @mbggenerated Mon Feb 27 22:23:57 CST 2017
     */
    public void setTips(String tips) {
        this.tips = tips;
    }
}